name: linters
on:
  pull_request:
    branches:
    - master
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Check licenses
      run: | 
        make add-license
        clean=$(git status --porcelain --untracked-files=no | awk '{print $NF}')
        if [[ -n "${clean}" ]]; then
          echo "Files without license found"
          echo $clean
          markdown_content=$(printf "%s\n" "${clean}" | sed 's/^/- /')
          {
            echo "### :warning: Files Without License"
            echo ""
            echo "${markdown_content}"
          } >> $GITHUB_STEP_SUMMARY
          exit 1
        fi